### ISSUE TITLE
keep extension running on page reload

### ISSUE THREAD

**Issue by lentychang** [chainsawriot/hansolo#4]
[Potential Solutions](https://stackoverflow.com/questions/39843647/keep-chrome-extension-running-on-page-reload)

**Comment by chainsawriot** [comment]
Another solution is to make it a [userscript](https://www.tampermonkey.net/scripts.php). Like I did with this one.

https://github.com/chainsawriot/cranitup

It's fairly easy to convert a userscript to a plugin, either Firefox or Chrome.

**Comment by lentychang** [comment]
Cool! much easier. Then I close it.
